// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXgLUt8cGGJ3BmSBzacSjzI0bjCtBf8cM',
    appId: '1:331540286697:web:9caf383466ade098c07478',
    messagingSenderId: '331540286697',
    projectId: 'motoconnect-c3412',
    authDomain: 'motoconnect-c3412.firebaseapp.com',
    storageBucket: 'motoconnect-c3412.firebasestorage.app',
    measurementId: 'G-KW69FSB7CP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZZ8Bes-IbF2AV2tZxwkaEZgdKUM7coBw',
    appId: '1:331540286697:android:07b80248b67312b0c07478',
    messagingSenderId: '331540286697',
    projectId: 'motoconnect-c3412',
    storageBucket: 'motoconnect-c3412.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwcKMtc62hLDHsZOxhmRFlhtepZ-mC5L0',
    appId: '1:331540286697:ios:067c4eed59df3be3c07478',
    messagingSenderId: '331540286697',
    projectId: 'motoconnect-c3412',
    storageBucket: 'motoconnect-c3412.firebasestorage.app',
    iosBundleId: 'com.motoconnect.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwcKMtc62hLDHsZOxhmRFlhtepZ-mC5L0',
    appId: '1:331540286697:ios:067c4eed59df3be3c07478',
    messagingSenderId: '331540286697',
    projectId: 'motoconnect-c3412',
    storageBucket: 'motoconnect-c3412.firebasestorage.app',
    iosBundleId: 'com.motoconnect.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXgLUt8cGGJ3BmSBzacSjzI0bjCtBf8cM',
    appId: '1:331540286697:web:c2987a025dba4ec1c07478',
    messagingSenderId: '331540286697',
    projectId: 'motoconnect-c3412',
    authDomain: 'motoconnect-c3412.firebaseapp.com',
    storageBucket: 'motoconnect-c3412.firebasestorage.app',
    measurementId: 'G-1MEWPZNR61',
  );
}
